// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Webhook is an autogenerated mock type for the Webhook type
type Webhook struct {
	mock.Mock
}

// CommentsEvent provides a mock function with given fields: _a0
func (_m *Webhook) CommentsEvent(_a0 []byte) {
	_m.Called(_a0)
}

// IssuesEvent provides a mock function with given fields: _a0
func (_m *Webhook) IssuesEvent(_a0 []byte) {
	_m.Called(_a0)
}

// MergeRequestEvent provides a mock function with given fields: _a0
func (_m *Webhook) MergeRequestEvent(_a0 []byte) {
	_m.Called(_a0)
}

// TagPushEvent provides a mock function with given fields: _a0
func (_m *Webhook) TagPushEvent(_a0 []byte) {
	_m.Called(_a0)
}
