// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import http "net/http"
import mock "github.com/stretchr/testify/mock"

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// Get provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *Client) Get(_a0 string, _a1 map[string]string, _a2 map[string]string, _a3 map[string]string) (*http.Response, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	var r0 *http.Response
	if rf, ok := ret.Get(0).(func(string, map[string]string, map[string]string, map[string]string) *http.Response); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, map[string]string, map[string]string, map[string]string) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Post provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *Client) Post(_a0 string, _a1 map[string]string, _a2 map[string]string, _a3 map[string]string) (*http.Response, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	var r0 *http.Response
	if rf, ok := ret.Get(0).(func(string, map[string]string, map[string]string, map[string]string) *http.Response); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, map[string]string, map[string]string, map[string]string) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
